name: 构建Docker测试

on:
  push:
    branches: [ 'main' ]
    paths: [ 'Dockerfile.test' ]

jobs:
  build-docker:
    name: 构建Docker
    runs-on: ubuntu-latest
    env:
      TAG_LIST: dr34m/docker-test:v0.0.1-test

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: 登录到DockerHub
        uses: docker/login-action@v3
        with:
          username: dr34m
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.test
          push: false
          tags: ${{ env.TAG_LIST }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386,linux/arm/v6,linux/s390x,linux/ppc64le

      - name: 读取镜像
        run: |
          docker images -a