name: docker测试构建

on:
  push:
    branches: [ 'main' ]
    paths: [ '.github/workflows/buildDockerTest.yml' ]

env:
  DOCKER_USER: dr34m
  DOCKER_NAME: python-action-demo

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 设置Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: 登录到DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.test
          tags: ${{ env.DOCKER_USER }}/${{ env.DOCKER_NAME }}:test